const mockAthletes = [
  {
    id: 1,
    first_name: "Max",
    last_name: "Mustermann",
    email: "testmail.de",
    birthdate: "2000-01-01",
    gender: "m",
  },
  {
    id: 2,
    first_name: "Erika",
    last_name: "Musterfrau",
    email: "erika@mail.de",
    birthdate: "1995-06-15",
    gender: "f",
  },
  {
    id: 3,
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    birthdate: "1988-03-22",
    gender: "m",
  },
  {
    id: 4,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 5,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 6,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 7,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 8,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 9,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
  {
    id: 10,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    birthdate: "1992-09-10",
    gender: "f",
  },
];
export { mockAthletes };
