name: Build Frontend

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install Node.js dependencies
        run: npm ci

  linting:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Lint through project
        run: npm run lint

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Build the Frontend
        run: npm run build
