name: Build Frontend

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup_project.yml
    with:
      node-version: 23
    steps:
      - name: Lint through project
        run: npm run lint

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint
    # if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/setup_project.yml
    with:
      node-version: 23
    steps:
      - name: Build the Frontend
        run: npm run build
