name: Build Frontend

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Lint through project
        run: npm run lint

  check-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref != 'refs/heads/main' && github.event_name != 'workflow_dispatch'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Build Frontend
        run: npm run build

  publish-build-prod:
    name: Publish Production Frontend
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Build Frontend
        env:
          VITE_BACKEND_BASE_URL: ${{ vars.MEDALS_BACKEND_BASE_URL }}
          VITE_BACKEND_BROKER_URL: ${{ vars.MEDALS_BACKEND_BROKER_URL }}
          VITE_WEBSOCKET_FACTORY: ${{ vars.MEDALS_WEBSOCKET_FACTORY }}
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.MEDALS_DOCKER_USERNAME }}
          password: ${{ secrets.MEDALS_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend

      - name: Push Docker image
        run: docker push ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend

  publish-build-local:
    name: Publish Local-Use Frontend
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Build Frontend
        env:
          VITE_BACKEND_BASE_URL: http://localhost:1024/api/v1
          VITE_BACKEND_BROKER_URL: ws://localhost:1024/api/v1/ws
          VITE_WEBSOCKET_FACTORY: http://localhost:1024/api/v1/ws
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.MEDALS_DOCKER_USERNAME }}
          password: ${{ secrets.MEDALS_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend:local

      - name: Push Docker image
        run: docker push ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend:local
