name: Build Frontend

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint through project
        run: npm run lint

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: setup
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Build the Frontend
        run: npm run build
