name: Build Frontend

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 23

      - name: Lint through project
        run: npm run lint

  check-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 23

      - name: Build Frontend
        run: npm run build

  publish-image:
    name: Publish Frontend
    runs-on: ubuntu-latest
    needs: lint
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup medals-frontend
        uses: ./.github/actions/setup
        with:
          node-version: 23

      - name: Build Frontend
        env:
          VITE_BACKEND_BASE_URL: ${{ secrets.MEDALS_BACKEND_BASE_URL }}
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.MEDALS_DOCKER_USERNAME }}
          password: ${{ secrets.MEDALS_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend

      - name: Push Docker image
        run: docker push ${{vars.MEDALS_DOCKER_USERNAME}}/medals-frontend
