name: Linter

on: push

jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install Node.js dependencies
        run: npm i

      - name: Lint through project
        run: npm run lint
